apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  tasks:
    - name: install-dependencies
      taskRef:
        name: npm-install

    - name: run-tests
      taskRef:
        name: run-tests
      runAfter:
        - install-dependencies

    - name: build-image
      taskRef:
        name: build-task
      runAfter:
        - run-tests
